INSERT INTO [dbo].[Exercise] ([Name], [Difficulty], [Set], [Reps]) VALUES (N' Bent-Over Row', 5, 3, 6)
INSERT INTO [dbo].[Exercise] ([Name], [Difficulty], [Set], [Reps]) VALUES (N'Bench Fly', 4, 4, 8)
INSERT INTO [dbo].[Exercise] ([Name], [Difficulty], [Set], [Reps]) VALUES (N'Bench Press', 5, 3, 5)
INSERT INTO [dbo].[Exercise] ([Name], [Difficulty], [Set], [Reps]) VALUES (N'Biceps with Barbell', 3, 3, 4)
INSERT INTO [dbo].[Exercise] ([Name], [Difficulty], [Set], [Reps]) VALUES (N'Biceps with Dumbbell', 3, 3, 6)
INSERT INTO [dbo].[Exercise] ([Name], [Difficulty], [Set], [Reps]) VALUES (N'Close-Grip Bench Press ', 5, 3, 10)
INSERT INTO [dbo].[Exercise] ([Name], [Difficulty], [Set], [Reps]) VALUES (N'Crunch', 1, 2, 50)
INSERT INTO [dbo].[Exercise] ([Name], [Difficulty], [Set], [Reps]) VALUES (N'Deadbug', 3, 4, 15)
INSERT INTO [dbo].[Exercise] ([Name], [Difficulty], [Set], [Reps]) VALUES (N'Dead-Lift', 5, 3, 4)
INSERT INTO [dbo].[Exercise] ([Name], [Difficulty], [Set], [Reps]) VALUES (N'Plank', 4, 3, 60)
INSERT INTO [dbo].[Exercise] ([Name], [Difficulty], [Set], [Reps]) VALUES (N'Pull Over with Dumbbell', 5, 3, 1)
INSERT INTO [dbo].[Exercise] ([Name], [Difficulty], [Set], [Reps]) VALUES (N'Seated Calf Raise', 3, 4, 20)
INSERT INTO [dbo].[Exercise] ([Name], [Difficulty], [Set], [Reps]) VALUES (N'Sit up', 2, 4, 25)
INSERT INTO [dbo].[Exercise] ([Name], [Difficulty], [Set], [Reps]) VALUES (N'Squat', 1, 4, 25)
INSERT INTO [dbo].[Exercise] ([Name], [Difficulty], [Set], [Reps]) VALUES (N'Squat with Barbell', 5, 3, 6)
INSERT INTO [dbo].[Exercise] ([Name], [Difficulty], [Set], [Reps]) VALUES (N'Triceps with Dumbbell', 3, 4, 12)
INSERT INTO [dbo].[Exercise] ([Name], [Difficulty], [Set], [Reps]) VALUES (N'Upright Row with  Dumbbell', 2, 4, 12)
